### ISSUE TITLE
Potential missed ListingCreated events

### ISSUE THREAD

**Issue by mikeshultz** [OriginProtocol/dshop#345] opened 2020-07-31 00:50 UTC
Seen a few occurrences of this in prod recently.  I don't know if this is causing issues or is intentional.  Just looks weird to me.

    [INFO]  dshop.utils.handleLog: Event ListingCreated for listing Id 1-001-2465
    [DEBUG] dshop.utils.handleLog: Event is not for a registered dshop. Skipping.

The listing JSON [does appear to be a Dshop listing](https://fs.ogn.app/ipfs/QmfPimnYhWSay6AXYMUnrx4LX3nMHoskbrvetFdEdysbMR):

    {
      "__typename": "UnitListing",
      "schemaId": "https://schema.originprotocol.com/listing_3.0.0.json",
      "listingType": "unit",
      "category": "schema.forSale",
      "subCategory": "schema.clothingAccessories",
      "language": "en-US",
      "description": "Origin DShop Store",
      "media": [],
      "price": {
        "amount": "0",
        "currency": "fiat-USD"
      },
      "amount": "0",
      "currency": "fiat-USD",
      "acceptedTokens": ["token-ETH"],
      "commission": {
        "currency": "OGN",
        "amount": "0"
      },
      "commissionPerUnit": {
        "currency": "OGN",
        "amount": "0"
      },
      "requiresShipping": false,
      "unitsTotal": 1000
    } 

Could be from a custom deployment, which would make this sane and okay.  There's no DB entries matching this listing(may or may not be expected).  The numbers aren't really expected, however.

**Comment by franckc** [comment] 2020-07-31 04:28
I wonder if this is a race condition:
 - A listing is created for a new shop on the front-end via MetaMask
 - Transaction get mined
 - The back-end listener may pick up the event faster than the front-end
 - In that case the front-end won't have updated listing_id in the shops table, which would explain why the listener does not find it...

The good news is that the logic does not process ListingCreated event (only Offer events are). See [code](https://github.com/OriginProtocol/dshop/blob/master/backend/utils/handleLog.js#L242).

One minor impact though is that we won't record that event in the DB which down the road could be useful. See [code](https://github.com/OriginProtocol/dshop/blob/master/backend/utils/handleLog.js#L97).

**Comment by franckc** [comment] 2020-07-31 04:32
Now, I checked the DB and I don't see any row in the shops table associated with listing id 1-001-2465.
It's possible the user did not wait for the transaction to be mined before killer their browser tab running the dshop deployer, resulting in the front-end not registering the listing id with the back-end?

**Comment by franckc** [comment] 2020-07-31 04:43
I'm actually seeing a lot of holes in the sequence of listing ids registered with the back-end in the shops table.
```
select id, created_at, listing_id from shops order by listing_id desc;
...
 328 | 2020-07-31 04:19:28.859+00 | 1-001-2488
 304 | 2020-07-31 02:33:14.842+00 | 1-001-2486
 297 | 2020-07-31 01:55:52.233+00 | 1-001-2480
 276 | 2020-07-31 00:47:10.941+00 | 1-001-2479
 292 | 2020-07-31 01:31:21.013+00 | 1-001-2478
 271 | 2020-07-31 00:35:05.692+00 | 1-001-2474
 280 | 2020-07-31 00:57:06.253+00 | 1-001-2473
 240 | 2020-07-30 23:30:04.903+00 | 1-001-2471
 194 | 2020-07-25 17:52:10.445+00 | 1-001-2469
 263 | 2020-07-31 00:06:46.916+00 | 1-001-2468
 242 | 2020-07-30 23:36:34.329+00 | 1-001-2466
 218 | 2020-07-30 23:14:25.186+00 | 1-001-2463
 211 | 2020-07-30 22:17:27.288+00 | 1-001-2460
```

This could indicate a bug in the front-end where it does not register the listing id with the back-end ?

**Comment by franckc** [comment] 2020-07-31 05:19
Something odd. 

These server logs indicates that there was a shop with listing_id 1-001-2476. Otherwise the Upsert event would not have happened (see [this code](https://github.com/OriginProtocol/dshop/blob/master/backend/utils/handleLog.js#L90)).
```
I 2020-07-31T01:33:56.276293250Z [INFO]  dshop.utils.handleLog: Event ListingCreated for listing Id 1-001-2476
I 2020-07-31T01:33:56.280307432Z [DEBUG] dshop.utils.events: Upsert event...
 ```
And querying the DB confirms an event for listing id 2476 was inserted in the events table.

BUT when querying the shops table, I do not see any shop associated with that listing!
```
dshop=> select id, created_at, name from shops where listing_id='1-001-2476';
 id | created_at | name 
----+------------+------
(0 rows)
```

This could indicate that after that event got inserted, the shop got updated and the listing_id deleted from the shop DB row?

**Comment by franckc** [comment] 2020-07-31 05:39
Confirmed that listing id 2476, 2477, 2478 were created by the same address  starting with 0xde7245...
So that would explain the holes in the listing ids in the shops table for that range of listing Ids.
I wonder what causes that user to create 3 listings?

I'll check for other listing Id ranges.

**Comment by nick** [comment] 2020-07-31 15:27
The current mechanism of waiting for the tx to be mined, then updating the backend via the UI isn't great. Instead, we could do the following:

* Add a listingCreatedTx column to the shops db table
* Send the txHash and owner wallet to the backend from the UI as soon as we get it (ie don't wait for it to be mined)
* Listener watches for ListingCreated events, and updates any shops in the db with matching tx + owner with the eventually mined listingId

**Comment by nick** [comment] 2020-07-31 15:42
Caveat: if the user 'speeds up' the transaction, a new txHash will be generated but the old txHash could still be mined first. For that reason we should probably have the ability to either a) monitor multiple txHashes for the same shop on the backend, or b) find the shop that has the same sellerWallet as in the ListingCreated event, but with no listingId yet, and update that. 

The former is more complex but probably better, as users could conceivably try to create multiple shops in quick succession

**Comment by franckc** [comment] 2020-07-31 18:48
I looked at another range of listing ids and it has a similar pattern.
Listing Ids range [1-991-2497, 1-991-2499].
All those 3 listings were created by the same shop (id 374).

It seems a pretty common pattern so worth putting in a fix.
I'll look at the backend piece and then we can integrate the front-end.

**Comment by franckc** [comment] 2020-09-25 18:45
Lowering to P2 since now that we moved things off-chain, the listener is not involved for setting up a shop and orders processing.

**Comment by franckc** [comment] 2020-10-26 16:58
Closing this code is not active in prod and therefore we don't have any new data to investigate on.

**Closed by franckc** 2020-10-26 16:58 UTC
Labels: P2, backend, bug
