### ISSUE TITLE
Purchasing hangs for 35 seconds, then crashes

### ISSUE THREAD

**Issue by DanielVF** [OriginProtocol/dshop#46] opened 2020-05-26 11:40 UTC
Somehow, I still have no origin swag. And I needed a good t-shirt. So I went to the Origin Swag Store to order one, and things crashed and burned when placing the order. 🔥 🚗 

What happened:

- Picked out a shirt, added to cart, filled in my info, shipping, and payment info.
- Clicking the payment button seemed to "hang" for a tiny bit. Nothing happened on the page for too long. I was going to make a bug report that we should add some kind of display that processing is happening in the background after the button click.
- After too long, the whole page changed to what I think was a white page with "loading" displayed
 - Then it eventually crashed to a white page with nothing on it.

![image](https://user-images.githubusercontent.com/837/82895007-88700000-9f21-11ea-9500-f0a08bbd2adc.png)

I still could use another T-shirt. Here goes another order with and open network tab and full profiling running. Results:

- After clicking the "Pay $20.00" button, the button color changed slightly about 25ms later.
- It did crypto stuff for about 250ms. (no screen change)
- It took 2000ms to post to our IPFS. We've got something wrong there then. (no screen change)
- It took 612ms to pay at swag.ogn.app
- 2700ms for confirm at api.stripe.com
- Roughly five and a half seconds after clicking "pay", the screen changed to a "Loading" page.
- This loading page lasted 30 seconds! It was attempting to load https://originswag.eth.link/dist/4.0f591475.bundle.js
- I actually got my purchase order email while the screen still said "loading"
- That bundle request failed. This white screened the app.

Issues:

- Posting to IPFS is taking way too long
- We need a better progress view after clicking "Pay". Even a second is too long to wait without some kind of spinner thing.
- Requesting https://originswag.eth.link/dist/4.0f591475.bundle.js is broken. I can't get that file.
- Why do we go to a "loading" screen after purchase, anyway?

**Comment by franckc** [comment] 2020-05-26 16:53
@nick Is this a known issue? Is originswag.eth.link pointing to the latest version of the code?

**Comment by nick** [comment] 2020-05-26 18:44
No it's super old. Will be updating it soon 😊

**Comment by franckc** [comment] 2020-06-08 17:29
Assigning to Nick since he's working on upgrading the swag shop and migrating it to the new GCP backend.

**Comment by franckc** [comment] 2020-06-19 17:24
@DanielVF This should now be fixed since @nick upgraded the swag store. Closing it but please re-open if you are able to reproduce.

**Closed by franckc** 2020-06-19 17:24 UTC
Labels: P0, bug
