### ISSUE TITLE
Inconsistent pricing from homepage to product page

### ISSUE THREAD

**Issue by micahalcorn** [OriginProtocol/dshop#261] opened 2020-07-17 17:25 UTC
I have a product with two variants, each with a different price.

Product price: $12.34
Variant A price: $13.57
Variant B price: $12.34

The price shown on my homepage will be $12.34 but, when I click on the product, I will see a default of $13.57 on the product page, which is confusing for the buyer. There are a few different ways we could go with this.

1. Allow for arrangement of the variants so that the seller has control over the sorting when they're displayed. This isn't really the proper fix for the pricing confusion, but it has its own merits anyway.
2. Show a range of prices on the index page. This might end up producing messier UI.
3. Default to no selection on the product page. It would be clearer if the buyer was forced to make a selection.

Related to this, it's possible for the seller to inadvertently set variant prices that don't match the product price at all. Perhaps the "product price" should be disabled if the variant price fields are used or if variants exist at all.

**Comment by gullible1** [comment] 2020-08-11 16:24
Closing as duplicate of #409 .

**Closed by gullible1** 2020-08-11 16:24 UTC
Labels: ui/ux
