### ISSUE TITLE
Nothing happens after clicking "place order" button despite order going through 

### ISSUE THREAD

**Issue by gullible1** [OriginProtocol/dshop#573] opened 2020-09-25 03:10 UTC
Upon clicking "place order" on the last step of the checkout flow, the button changes to "processing" briefly before reverting back to "place order". The order has gone through successfully as I've received a confirmation email, but I'm not taken to the thank you page.

This can be confusing for users and we had a recent customer who clicked on the button twice and ended up buying the same item twice (Order # 1-001-2445-22 on Pundi-x.ogn.app).

https://www.loom.com/share/03963caea47a4ac888b1e6fd9c7f16ff

**Comment by franckc** [comment] 2020-09-29 03:47
@shahthepro If you have some bandwidth, this could be a great issue to prioritize working on since it looks it caused some duplicate payments (see post from Nick in the discord channel) in production.

I checked the back-end and I'm seeing the same order being posted twice by the front-end. So I think it's likely to be that somehow the front-end is allowing the user to click twice on the "Pay" button.

CC @nick since he was looking at it today but afaict hasn't made progress on it.

**Comment by shahthepro** [comment] 2020-09-29 03:48
Will pick this up @franckc. Anyway to consistently reproduce this? On local or prod?

**Comment by franckc** [comment] 2020-09-29 03:59
Thanks @shahthepro - no consistent way to reproduce afaik :(

**Comment by shahthepro** [comment] 2020-09-29 04:00
Guess, will spam orders on Anna's store then :)

**Comment by micahalcorn** [comment] 2021-02-05 07:44
I'm going to close this one assuming that it can't be reproduced or was resolved.

**Closed by micahalcorn** 2021-02-05 07:44 UTC
Labels: P2, bug
